[project]
name = "auth-service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "ravinderdhokwal", email = "ravindercodes@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "alembic>=1.19.1",
    "asyncpg>=0.31.0",
    "bcrypt>=5.0.0",
    "email-validator>=2.3.0",
    "fastapi>=0.141.1",
    "pydantic>=2.13.4",
    "pydantic-settings>=2.15.0",
    "sqlalchemy[asyncio]>=2.0.52",
    "uvicorn[standard]>=0.52.4",
]

[project.scripts]
auth-service = "auth_service:main"

[build-system]
requires = ["uv_build>=0.10.11,<0.11.0"]
build-backend = "uv_build"
